from selenium import webdriver
driver= webdriver.Chrome(executable_path ='absolute path for chromedriver')
driver
driver.get("https://www.google.co.in")
driver.maximize_window()
c=driver.find_element_by_name("q")
c.click()
c.clear()
c.send_keys("gmail sign in")
c.submit()
d=driver.find_element_by_class_name("LC20lb")
d.click()
e=driver.find_element_by_id("identifierId")
e.click()
e.send_keys('******')
f=driver.find_element_by_class_name("CwaK9")
f.click()
driver.implicitly_wait(10)
g=driver.find_element_by_name('password')
g.click()
g.clear()
g.send_keys('*****
h=driver.find_element_by_class_name('CwaK9')
h.click()
