from selenium import webdriver
driver= webdriver.Chrome(executable_path ='absolute path for chromedriver')
driver
driver.get("https://www.google.co.in")
driver.maximize_window()
gmailid=driver.find_element_by_name("q")
gmailid.click()
gmailid.clear()
gmailid.send_keys("gmail sign in")
gmailid.submit()
username=driver.find_element_by_class_name("LC20lb")
username.click()
username=driver.find_element_by_id("identifierId")
username.click()
username.send_keys('******')
password=driver.find_element_by_class_name("CwaK9")
password.click()
driver.implicitly_wait(10)
password=driver.find_element_by_name('password')
password.click()
password.clear()
password.send_keys('*****')
signin=driver.find_element_by_class_name('CwaK9')
signin.click()
driver.close()
